; Name:     ES3-05  platformio.ini
; Updated:  2026-05-13

;PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]

; Chose a default source directory, if different from "src"
src_dir = main

; chose environment:
default_envs = esp32

; ============================================================

[env]

; defines which SDK you're using — Arduino or ESP-IDF.
framework = arduino

; identifies your exact board model.
board = WaveShare-esp32-s3-ETH

upload_speed = 921600
upload_port = /dev/ttyACM0

monitor_speed = 115200
monitor_port = /dev/ttyACM0

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
board_build.extra_flags =
  ; --- only for boards with PSRAM:
  -DBOARD_HAS_PSRAM
  ;
  -DARDUINO_USB_CDC_ON_BOOT=1
  ; 0 no debug output, 1 errors, 2 warnings, 3 infos, 4 debug info, 5 verbose
  -DCORE_DEBUG_LEVEL=3

; Checks for the compatibility with frameworks and dev/platforms
; You have to experiment to see which combination is working for you
lib_compat_mode = strict
lib_ldf_mode = chain+
;lib_ldf_mode = deep+

lib_deps =
; PlatformIO 4.x

; PlatformIO 5.x


build_flags =
; set your debug output (default=Serial)
; -D DEBUG_ESP_PORT=Serial
; comment the following line to enable WiFi debugging
; -D NDEBUG

; ============================================================

[env:esp8266]
; specifies the chipset family (ESP32)
platform = espressif8266

; identifies your exact board model.
board = nodemcuv2

; defines which SDK you're using — Arduino or ESP-IDF.
framework = arduino

; ============================================================

[env:esp32]
; specifies the chipset family (ESP32)
platform = espressif32

; identifies your exact board model.
board = esp32-s3-devkitc-1

; defines which SDK you're using — Arduino or ESP-IDF.
framework = arduino

upload_speed = 921600
upload_port = /dev/ttyACM0

monitor_speed = 115200
monitor_port = /dev/ttyACM0

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
board_build.extra_flags =
  ; --- only for boards with PSRAM:
  -DBOARD_HAS_PSRAM
  ;
  -DARDUINO_USB_CDC_ON_BOOT=1
  ; 0 no debug output, 1 errors, 2 warnings, 3 infos, 4 debug info, 5 verbose
  -DCORE_DEBUG_LEVEL=3

lib_deps =
  ${env.lib_deps}  ; Inherit common dependencies
  https://github.com/adafruit/Adafruit_NeoPixel.git
  ; https://github.com/arduino-libraries/Ethernet.git#v2.0.2
  Ethernet@^2.0.2

  ; https://github.com/espressif/arduino-esp32/tree/master/libraries/SD

; ============================================================

; default env(s) to be built
; default_envs = release
; default_envs = debug

; ============================================================

; Custom data group
; can be use in [env:***] via ${common.***}
[common]

; Global data shared between all [env:NAME] environments

;=========================================================================================;

; ### END DBK
