; Name:     ES3-05  platformio.ini
; Updated:  2026-05-29
;
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
; https://docs.platformio.org/en/latest/boards/espressif32/esp32-s3-devkitc-1.html
; https://docs.espressif.com/projects/esptool/en/latest/esp32/esptool/configuration-file.html#configuration-file

[platformio]
default_envs = ES3-05


[common]
build_flags =
    -D VERSION=1.0.0
    -D DEBUG=1


[env:ES3-05]
framework = arduino
board = esp32-s3-devkitc-1
platform = espressif32

; Microcontroller:  ESP32S3
; Frequency:        240MHz
; Flash:            8MB
; RAM:              320KB
; Vendor:           Espressif

; change microcontroller
board_build.mcu = esp32s3

; change MCU frequency
board_build.f_cpu = 240000000L

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = partitions.csv

upload_port = /dev/ttyACM0
upload_speed = 115200

; ===== Supported upload protocols:
; cmsis-dap
; esp-bridge
; esp-builtin
; esp-prog
; espota
; esptool
; iot-bus-jtag
; jlink
; minimodule
; olimex-arm-usb-ocd
; olimex-arm-usb-ocd-h
; olimex-arm-usb-tiny-h
; olimex-jtag-tiny
; tumpa
; -----
upload_protocol = esptool

; ===== Monitor options
monitor_speed = 115200
monitor_port = /dev/ttyACM0

board_build.extra_flags =
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CORE_DEBUG_LEVEL=3

lib_compat_mode = strict
lib_ldf_mode = chain+

lib_deps =
    ; ${env.lib_deps}
    https://github.com/adafruit/Adafruit_NeoPixel.git
    arduino-libraries/WiFi@^1.2.7
    arduino-libraries/Ethernet@^2.0.2

; ### END DBK
